from __future__ import annotations

COMMON_CSS='''<style>
:root{--bg:#f4f7fb;--fg:#152033;--muted:#6a7487;--card:#fff;--line:#dce3ee;--accent:#172033;--good:#147a47;--bad:#b42318}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.5 Inter,system-ui,sans-serif}.shell{max-width:1380px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;gap:16px;align-items:end;margin-bottom:20px}.brand{font-size:32px;font-weight:900;letter-spacing:-.05em}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px}.card{background:var(--card);border:1px solid var(--line);border-radius:18px;padding:18px;box-shadow:0 8px 30px #1520330b}.card h2{margin:0 0 8px;font-size:18px}.metric{font-size:28px;font-weight:900}.row{display:flex;justify-content:space-between;gap:8px;align-items:center}.btn{border:0;border-radius:10px;padding:9px 12px;cursor:pointer}.primary{background:var(--accent);color:#fff}.secondary{background:#e9eef6}.danger{background:#fee4e2;color:var(--bad)}input,select,textarea{width:100%;padding:9px;border:1px solid #cbd5e1;border-radius:10px;margin:5px 0 10px}.item{border:1px solid #e4e9f1;border-radius:12px;padding:10px;margin:7px 0}.pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#eef2f6;font-size:12px}.ok{background:#e8f7ef;color:var(--good)}.bad{background:#fee4e2;color:var(--bad)}pre{white-space:pre-wrap;max-height:340px;overflow:auto;background:#0e1522;color:#e9eef7;padding:12px;border-radius:12px}.nav{display:flex;gap:7px;flex-wrap:wrap;margin:15px 0}.nav button{border:1px solid var(--line);background:#fff;border-radius:10px;padding:8px 11px;cursor:pointer}.section{display:none}.section.active{display:block}.small{font-size:12px}
</style>'''

def page(principal):
    is_host=principal=='host'
    nav=['Overview','Recommendations','Research','Skills','Knowledge'] if principal=='agent' else ['Overview','Configuration','Security','Federation','Ecosystem','Knowledge'] if is_host else ['Overview','Marketplace','Knowledge']
    buttons=''.join(f'<button onclick="show(\'{n.lower()}\')">{n}</button>' for n in nav)
    panels='''<section id="overview" class="section active"><div class="grid"><div class="card"><div class="muted">Identity</div><div id="me" class="metric">…</div></div><div class="card"><div class="muted">Health</div><div id="health" class="metric">…</div></div><div class="card"><div class="muted">Trust / mode</div><div id="mode" class="metric">…</div></div></div><div class="card"><h2>Agent-readable state</h2><pre id="state">loading…</pre></div></section>'''
    if principal=='agent':
        panels+='''<section id="recommendations" class="section"><div class="card"><h2>Skill Router</h2><input id="task" placeholder="Describe the task"><button class="btn primary" onclick="recommend()">Recommend</button><pre id="rec"></pre></div><div class="card"><h2>Team planner</h2><textarea id="team" rows="7">{"objective":"solve task","members":[{"agent_id":"self","role":"worker","weight":1,"capabilities":["coding"]}],"tasks":["investigate","implement","verify"],"required_capabilities":["coding"]}</textarea><button class="btn secondary" onclick="teamplan()">Plan</button><pre id="teamout"></pre></div></section>'''
        panels+='''<section id="research" class="section"><div class="card"><h2>Research loop</h2><textarea id="research" rows="5">{"observation":{"problem":"describe observation"},"agent":"self","skill":""}</textarea><button class="btn primary" onclick="research()">Create / run</button><pre id="researchout"></pre></div></section>'''
    if is_host:
        panels+='''<section id="configuration" class="section"><div class="card"><h2>Host customization</h2><textarea id="configpatch" rows="12">{"deployment_mode":"personal","node_id":"local","host_custom":{"brand":"skIF","theme":"light"},"prediction_market_enabled":false,"resource_governance":{"max_usd":10,"max_tokens":100000,"max_seconds":900,"max_concurrent":4}}</textarea><button class="btn primary" onclick="saveConfig()">Save</button><pre id="cfgout"></pre></div></section>'''
        panels+='''<section id="security" class="section"><div class="grid"><div class="card"><h2>Continuous fuzz</h2><button class="btn danger" onclick="fuzz()">Run</button><pre id="fuzzout"></pre></div><div class="card"><h2>Supply chain</h2><textarea id="deps">["requests==2.32.3","example@latest"]</textarea><button class="btn secondary" onclick="supply()">Scan</button><pre id="supplyout"></pre></div><div class="card"><h2>Sandbox</h2><textarea id="cmds">["echo safe","rm -rf /"]</textarea><button class="btn secondary" onclick="sandbox()">Scan</button><pre id="sandboxout"></pre></div></div></section>'''
        panels+='''<section id="federation" class="section"><div class="card"><h2>Federation</h2><textarea id="fed" rows="7">{"node_id":"peer","url":"https://peer.example","policy":{"security":"gold","reliability":0.8,"require_signed":true,"require_portable_identity":true}}</textarea><button class="btn primary" onclick="connect()">Negotiate / connect</button><pre id="fedout"></pre></div></section>'''
        panels+='''<section id="ecosystem" class="section"><div class="card"><h2>Resource governance</h2><textarea id="resource">{"estimate":{"usd":1,"tokens":1000,"seconds":10,"concurrent":1}}</textarea><button class="btn secondary" onclick="admit()">Admit</button><pre id="resourceout"></pre></div></section>'''
    panels+='''<section id="skills" class="section"><div class="card"><h2>Skill Marketplace</h2><input id="q" placeholder="search"><button class="btn primary" onclick="searchSkills()">Search</button><pre id="skillsout"></pre></div></section>'''
    panels+='''<section id="marketplace" class="section"><div class="card"><h2>Marketplace</h2><input id="mq" placeholder="search"><button class="btn primary" onclick="searchSkills('market')">Search</button><pre id="skillsout2"></pre></div></section>'''
    panels+='''<section id="knowledge" class="section"><div class="card"><h2>Knowledge Mesh</h2><div class="grid"><input id="source" placeholder="source"><input id="target" placeholder="target"></div><button class="btn secondary" onclick="meshPath()">Find path</button><pre id="kgout"></pre></div></section>'''
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>skIF {principal} console</title>{COMMON_CSS}</head><body><main class="shell"><div class="top"><div><div class="brand">skIF 3.1 Neo</div><div class="muted">{principal.capitalize()} Console · Agent Skill Network</div></div><span class="pill">{principal}</span></div><div class="nav">{buttons}</div>{panels}</main><script>
const K='skif_token'; const token=localStorage.getItem(K)||''; const H=()=>token?{{Authorization:'Bearer '+token}}:{{}};
async function api(path,opt={{}}){{opt.headers={{'Content-Type':'application/json',...H(),...(opt.headers||{{}})}};let r=await fetch(path,opt);let x=await r.json();if(!r.ok)throw new Error(JSON.stringify(x));return x}}
function show(id){{document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.getElementById(id)?.classList.add('active')}}
async function refresh(){{try{{let [me,h]=await Promise.all([api('/api/auth/me'),api('/api/health')]);document.getElementById('me').textContent=me.subject;document.getElementById('mode').textContent=me.mode+' / '+me.node_id;document.getElementById('health').textContent=h.ok?'OK':'ERR';document.getElementById('state').textContent=JSON.stringify({{me,health:h}},null,2)}}catch(e){{document.getElementById('state').textContent=e}}}}
async function recommend(){{let x=await api('/api/agent/recommend?task='+encodeURIComponent(document.getElementById('task').value));document.getElementById('rec').textContent=JSON.stringify(x,null,2)}}
async function teamplan(){{let x=await api('/api/agent/team/plan',{{method:'POST',body:document.getElementById('team').value}});document.getElementById('teamout').textContent=JSON.stringify(x,null,2)}}
async function research(){{let b=JSON.parse(document.getElementById('research').value);let x=await api('/api/autonomous/run',{{method:'POST',body:JSON.stringify({{skill:b.skill||'',loops:1,observation:b.observation,agent_id:b.agent,auto_evolve:false}})}});document.getElementById('researchout').textContent=JSON.stringify(x,null,2)}}
async function searchSkills(target=''){{let q=document.getElementById(target==='market'?'mq':'q').value;let x=await api('/api/marketplace/search?q='+encodeURIComponent(q));document.getElementById(target==='market'?'skillsout2':'skillsout').textContent=JSON.stringify(x,null,2)}}
async function meshPath(){{let s=document.getElementById('source').value,t=document.getElementById('target').value;let x=await api('/api/knowledge/mesh/path?source='+encodeURIComponent(s)+'&target='+encodeURIComponent(t));document.getElementById('kgout').textContent=JSON.stringify(x,null,2)}}
async function saveConfig(){{let x=await api('/api/onboarding',{{method:'POST',body:document.getElementById('configpatch').value}});document.getElementById('cfgout').textContent=JSON.stringify(x,null,2)}}
async function fuzz(){{let x=await api('/api/security/fuzz',{{method:'POST',body:JSON.stringify({{seed:{{probe:'neo'}},rounds:2,mutations:12}})}});document.getElementById('fuzzout').textContent=JSON.stringify(x,null,2)}}
async function supply(){{let x=await api('/api/security/supply-chain',{{method:'POST',body:JSON.stringify({{manifests:JSON.parse(document.getElementById('deps').value)}})}});document.getElementById('supplyout').textContent=JSON.stringify(x,null,2)}}
async function sandbox(){{let x=await api('/api/security/sandbox',{{method:'POST',body:JSON.stringify({{commands:JSON.parse(document.getElementById('cmds').value)}})}});document.getElementById('sandboxout').textContent=JSON.stringify(x,null,2)}}
async function connect(){{let b=JSON.parse(document.getElementById('fed').value);let x=await api('/api/federation/network/connect',{{method:'POST',body:JSON.stringify({{node_id:b.node_id,url:b.url,policy:b.policy}})}});document.getElementById('fedout').textContent=JSON.stringify(x,null,2)}}
async function admit(){{let b=JSON.parse(document.getElementById('resource').value);let x=await api('/api/resources/admit',{{method:'POST',body:JSON.stringify(b)}});document.getElementById('resourceout').textContent=JSON.stringify(x,null,2)}}
refresh();
</script></body></html>'''
